Spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/assignment?autoReconnect=true&useSSL=false
    username: root
    password: Pass$123_@2023
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update

---

server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: "/api/v1/"

---
spring:
  hateoas:
    use-hal-as-default-json-media-type: false